spring.profiles.active: develop
spring.datasource:
    url: ''
    username: ''
    password: ''

---
spring:
  config:
    activate:
      on-profile: staging
  datasource:
    url: ''
    username: ''
    password: ''
---
