spring.profiles.active: develop
spring.datasource:
    url: ''
    username: ''
    password: ''

---
spring:
  config:
    activate:
      on-profile: staging
  datasource:
    url: ''
    username: ''
    password: ''
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: 'jdbc:mysql://localhost:3306/crix'
    username: 'crix_user'
    password: 'crix123^'
